### ISSUE TITLE
Windows Defender blocks /removes download because of Trojan:Script/Wacatac.B!ml 

### ISSUE THREAD

**Issue by imm0r** [dliedke/D4Automator#1]
Hi,

i am pretty sure this is just a false positive but i wanted to let you know anyway.

![Wacatac B!ml](https://github.com/user-attachments/assets/34481ab9-bb53-40ac-be19-d95457de0384)

[VirusTotal](https://www.virustotal.com/gui/file/c10dced3f0225686cb675acc2dd9296bf50dbb470e9a5b3d2e50e63476e754df) also lists one security vendor that is detecting **_Trojan.Malware.300983.susgen_**.

**Comment by dliedke** [comment]
Thanks for the report, yes, it is a false positive, but there is not much I can do about it.
Even compiled as debug we have this issue. 
Have a nice weekend!
